FROM alpine:latest
RUN apk add --no-cache \
        python3 \
        py3-pip \
        mysql-client \
        mariadb-dev \
    && pip3 install --upgrade pip \
    && pip3 install --no-cache-dir awscli \
    && rm -fr /var/cache/apk/*
RUN aws --version
RUN mkdir /data
COPY --chmod=755 backup.sh /backup.sh
ENTRYPOINT /backup.sh
